### ISSUE TITLE
invalid command name "hla_serial"

### ISSUE THREAD

**Issue by BesitzeRuf** [STMicroelectronics/OpenOCD#16]
Hello,

as I know, the OpenOCD shall support the "hla_serial" command, it is also mentioned in [AN4989 Rev 3](https://www.st.com/resource/en/application_note/an4989-stm32-microcontroller-debug-toolbox-stmicroelectronics.pdf), but STM32CubeIDE 1.10.1 still generates error: invalid command name "hla_serial". 

Is it a bug or is there other way to use debugger with specific serial number?

**Comment by tarek-bochkati** [comment]
Dear @BesitzeRuf 

Thanks for reporting this, you are right the document is mentioning the command `hla_serial`, I will request a document update.
because `hla_serial` is not used anymore since older versions than v1.10.0.

The driver we are using provides a specific command `st-link serial`: you can use it with CubeIDE v1.10.0
But starting from CubeIDE v1.11.0, `st-link serial` is deprecated, and `adapter serial` should be used instead

(decided by OpenOCD community, as described in this commit : https://github.com/openocd-org/openocd/commit/c6460ea36d7eeaf4a0fe4fb1a4c65bb21547afbe#diff-38e18246b06ba7bebf728fdfbe71a0d3272c50cd8b4a8fd55b7afb370e5f28a2 )
